version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: sunset-app-laravel
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - postgres
  postgres:
    image: postgres
    container_name: sunset-postgres
    environment:
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
    ports:
      - "5455:5432"